package com.adamtrev.portal.data;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.joda.time.DateTime;

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
// should make this a constant based on deployment env variable
@DynamoDBTable(tableName = "DataStack-TestbedTable530D840A-83YRDM7PE8HC")
public class BillsPojo {
    @DynamoDBHashKey(attributeName = "pk")
    private String companyName;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBRangeKey(attributeName = "sk")
    private DateTime payableDate;

    @DynamoDBAttribute(attributeName = "cost")
    private Double cost;

    @DynamoDBTypeConvertedEpochDate
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private DateTime createdDate;

    @DynamoDBTypeConvertedEpochDate
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private DateTime lastModifiedDate;

    // enable optimistic locking
    @DynamoDBVersionAttribute(attributeName = "recordVersion")
    private Long recordVersion;
}

